In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Airline_Delay_Cause.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101315 entries, 0 to 101314
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Year                     101315 non-null  int64
 1   Month                    101315 non-null  int64
 2   AirlineCode              101315 non-null  object
 3   AirportCode              101315 non-null  object
 4   TotalFlights             101157 non-null  float64
 5   FlightsDelayedOver15Min  100960 non-null  float64
 6   CarrierDelayCount        101157 non-null  float64
 7   WeatherDelayCount        101157 non-null  float64
 8   NASDelayCount            101157 non-null  float64
 9   SecurityDelayCount       101157 non-null  float64
 10  LateAircraftDelayCount   101157 non-null  float64
 11  CancelledFlights         101157 non-null  float64
 12  DivertedFlights          101157 non-null  float64
 13  ArrivalDelayMinutes      101157 non-null  float64
dtypes: float64(10), int64(2), object(2)
memory usage: 10.8+ MB

In [4]:
df.isnull().sum()

Year                         0
Month                        0
AirlineCode                  0
AirportCode                  0
TotalFlights               158
FlightsDelayedOver15Min    355
CarrierDelayCount          158
WeatherDelayCount          158
NASDelayCount              158
SecurityDelayCount         158
LateAircraftDelayCount     158
CancelledFlights           158
DivertedFlights            158
ArrivalDelayMinutes        158
dtype: int64

In [5]:
df = df.dropna()
df = df.copy()
df.shape

(100960, 14)

In [6]:
df["AirlineCode"].unique()[:10]

array(['9E', 'AA', 'AS', 'B6', 'DL', 'F9', 'G4', 'HA', 'MQ', 'NK'],
      dtype=object)

In [7]:
df["AirportCode"].unique()[:10]

array(['ABE', 'ABY', 'ACK', 'AEX', 'AGS', 'ALB', 'ATL', 'ATW', 'AUS',
       'AVL'], dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le_airline = LabelEncoder()

In [10]:
df["AirlineCode"] = le_airline.fit_transform(df["AirlineCode"])

In [11]:
df["AirlineCode"].head()

0    0
1    0
2    0
3    0
4    0
Name: AirlineCode, dtype: int64

In [12]:
df["AirlineCode"].unique()[:10]

array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10])

In [13]:
le_airport = LabelEncoder()

In [14]:
df["AirportCode"] = le_airport.fit_transform(df["AirportCode"])

In [15]:
df["AirportCode"].head()

0     0
1     4
2     5
3    11
4    12
Name: AirportCode, dtype: int64

In [16]:
df.head()

,Year,Month,AirlineCode,AirportCode,TotalFlights,FlightsDelayedOver15Min,CarrierDelayCount,WeatherDelayCount,NASDelayCount,SecurityDelayCount,LateAircraftDelayCount,CancelledFlights,DivertedFlights,ArrivalDelayMinutes
0,2022,7,0,0,33.0,2.0,0.92,1.00,0.08,0.0,0.00,0.0,0.0,129.0
1,2022,7,0,4,78.0,25.0,11.80,0.72,5.01,0.0,7.48,0.0,0.0,1664.0
2,2022,7,0,5,124.0,19.0,5.84,1.00,6.76,0.0,5.40,5.0,4.0,1523.0
3,2022,7,0,11,67.0,10.0,1.32,1.00,2.40,1.0,4.28,0.0,1.0,657.0
4,2022,7,0,12,174.0,30.0,18.10,5.75,3.60,0.0,2.55,1.0,0.0,2462.0

In [17]:
df["Delayed"] = (df["ArrivalDelayMinutes"] > 15).astype(int)

In [18]:
df[["ArrivalDelayMinutes","Delayed"]].head()

   ArrivalDelayMinutes  Delayed
0                129.0        1
1               1664.0        1
2               1523.0        1
3                657.0        1
4               2462.0        1

In [19]:
X = df.drop (["ArrivalDelayMinutes", "Delayed"], axis = 1)

In [20]:
X.head()

,Year,Month,AirlineCode,AirportCode,TotalFlights,FlightsDelayedOver15Min,CarrierDelayCount,WeatherDelayCount,NASDelayCount,SecurityDelayCount,LateAircraftDelayCount,CancelledFlights,DivertedFlights
0,2022,7,0,0,33.0,2.0,0.92,1.00,0.08,0.0,0.00,0.0,0.0
1,2022,7,0,4,78.0,25.0,11.80,0.72,5.01,0.0,7.48,0.0,0.0
2,2022,7,0,5,124.0,19.0,5.84,1.00,6.76,0.0,5.40,5.0,4.0
3,2022,7,0,11,67.0,10.0,1.32,1.00,2.40,1.0,4.28,0.0,1.0
4,2022,7,0,12,174.0,30.0,18.10,5.75,3.60,0.0,2.55,1.0,0.0

In [21]:
y = df["Delayed"]

In [22]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: Delayed, dtype: int64

In [23]:
df.to_csv("cleaned_flight_delay.csv", index=False)